export const PROMPTS = {
  1: "One color, one shape.",
  2: "Layers upon layers upon layers",
  3: "Exactly 42 lines.",
  4: "Lowres. An image or graphic with low resolution, where details are simplified or pixelated.",
  5: "Isometric Art (No vanishing points).",
  6: "Lights on/off. Make something that changes when you switch on or off the “digital” lights.",
  7: "Progress bar / indicator / loading animation.",
  8: "Chaotic system.",
  9: "ASCII.",
  10: "You can only use TAU in your code, no other number allowed.",
  11: "In the style of Anni Albers (1899-1994).",
  12: "Lava lamp.",
  13: "Unexpected path. Draw a route that changes direction based on one very simple rule.",
  14: "Perfectionist's nightmare.",
  15: "Organic Geometry. Forms that look or act organic but are constructed entirely from geometric shapes.",
  16: "Recursive Grids. Split the canvas into a grid of some kind and recurse on each cell again and again.",
  17: "Lifeform. A shape or structure that behaves as if it's alive or growing.",
  18: "Its not a bug, its a feature.",
  19: "Grow a seed.",
  20: "Pixel sorting.",
  21: "Gradients only.",
  22: "Screensaver.",
  23: "A City. Create a generative metropolis.",
  24: "Boolean algebra. Get inspired by Boolean algebra, in any way.",
  25: "Genetic evolution and mutation.",
  26: "Pure black and white. No gray.",
  27: "Generative palette.",
  28: "Glitch Art.",
  29: "Debug view.",
  30: "Plants.",
  31: "Finale."
};